stages:
  - build
  - deploy

build-dev:
  image: docker:latest
  stage: build
  tags:
    - serempre
    - shell
  services:
    - docker:dind
  before_script:
    - rm -f ~/.docker/config.json
    - cp ${DEV_ENV_FILE} source/.env
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  only:
    - develop

build-stage:
  image: docker:latest
  stage: build
  tags:
    - serempre
    - shell
  services:
    - docker:dind
  before_script:
    - rm -f ~/.docker/config.json
    - cp ${STAGE_ENV_FILE} source/.env
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  only:
    - stage

deploy-dev:
  image: alpine
  stage: deploy
  tags:
    - docker
    - serempre
  script:
    - apk add --no-cache curl
    - curl -v -X POST https://docker.serempre.com/api/stacks/webhooks/8911d8af-1adc-46d5-854e-80d2a2b51852
  only:
    - develop

deploy-stage:
  image: alpine
  stage: deploy
  tags:
    - docker
    - serempre
  script:
    - apk add --no-cache curl
    - curl -v -X POST https://docker.serempre.com/api/stacks/webhooks/e9eabe56-5c76-46c0-a3b6-e51e637e7409
  only:
    - stage    
