version: '3.8'
services:
  vectorstore:
    image: chromadb/chroma
    ports:
      - "8081:8000"
    networks:
      - dappi_internal_network
  dappi:
    build: .
    ports:
      - "8080:8080"
    links:
      - vectorstore
    networks:
      - dappi_internal_network
networks:
   dappi_internal_network:
     driver: bridge
  
